/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartiesRouteImport } from './routes/parties'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as PartyPartyIdRouteImport } from './routes/party.$partyId'
import { Route as SiteSiteIdRouteImport } from './routes/site.$siteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesRoute = PartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyPartyIdRoute = PartyPartyIdRouteImport.update({
  id: '/party/$partyId',
  path: '/party/$partyId',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSiteIdRoute = SiteSiteIdRouteImport.update({
  id: '/site/$siteId',
  path: '/site/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/parties': typeof PartiesRoute
  '/reports': typeof ReportsRoute
  '/sites': typeof SitesRoute
  '/party/$partyId': typeof PartyPartyIdRoute
  '/site/$siteId': typeof SiteSiteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/parties': typeof PartiesRoute
  '/reports': typeof ReportsRoute
  '/sites': typeof SitesRoute
  '/party/$partyId': typeof PartyPartyIdRoute
  '/site/$siteId': typeof SiteSiteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/parties': typeof PartiesRoute
  '/reports': typeof ReportsRoute
  '/sites': typeof SitesRoute
  '/party/$partyId': typeof PartyPartyIdRoute
  '/site/$siteId': typeof SiteSiteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/parties'
    | '/reports'
    | '/sites'
    | '/party/$partyId'
    | '/site/$siteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/parties'
    | '/reports'
    | '/sites'
    | '/party/$partyId'
    | '/site/$siteId'
  id:
    | '__root__'
    | '/'
    | '/parties'
    | '/reports'
    | '/sites'
    | '/party/$partyId'
    | '/site/$siteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PartiesRoute: typeof PartiesRoute
  ReportsRoute: typeof ReportsRoute
  SitesRoute: typeof SitesRoute
  PartyPartyIdRoute: typeof PartyPartyIdRoute
  SiteSiteIdRoute: typeof SiteSiteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties': {
      id: '/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof PartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/$partyId': {
      id: '/party/$partyId'
      path: '/party/$partyId'
      fullPath: '/party/$partyId'
      preLoaderRoute: typeof PartyPartyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/$siteId': {
      id: '/site/$siteId'
      path: '/site/$siteId'
      fullPath: '/site/$siteId'
      preLoaderRoute: typeof SiteSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PartiesRoute: PartiesRoute,
  ReportsRoute: ReportsRoute,
  SitesRoute: SitesRoute,
  PartyPartyIdRoute: PartyPartyIdRoute,
  SiteSiteIdRoute: SiteSiteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
